<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Integrated Inferences Application | Integrated Inferences</title>
  <meta name="description" content="Bayesian causal models for integrated inferences." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Integrated Inferences Application | Integrated Inferences" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://macartan.github.io/integrated_inferences/" />
  <meta property="og:image" content="https://macartan.github.io/integrated_inferences//images/plot.png" />
  <meta property="og:description" content="Bayesian causal models for integrated inferences." />
  <meta name="github-repo" content="macartan/integrated_inferences" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Integrated Inferences Application | Integrated Inferences" />
  
  <meta name="twitter:description" content="Bayesian causal models for integrated inferences." />
  <meta name="twitter:image" content="https://macartan.github.io/integrated_inferences//images/plot.png" />

<meta name="author" content="Macartan Humphreys and Alan M. Jacobs" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="mixing.html"/>
<link rel="next" href="mm.html"/>
<script src="libs/header-attrs/header-attrs.js"></script>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="headers/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Integrated Inferences</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#the-case-for-causal-models"><i class="fa fa-check"></i><b>1.1</b> The Case for Causal Models</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#the-limits-to-design-based-inference"><i class="fa fa-check"></i><b>1.1.1</b> The limits to design-based inference</a></li>
<li class="chapter" data-level="1.1.2" data-path="intro.html"><a href="intro.html#qualitative-and-mixed-method-inference"><i class="fa fa-check"></i><b>1.1.2</b> Qualitative and mixed-method inference</a></li>
<li class="chapter" data-level="1.1.3" data-path="intro.html"><a href="intro.html#connecting-theory-and-empirics"><i class="fa fa-check"></i><b>1.1.3</b> Connecting theory and empirics</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#key-contributions"><i class="fa fa-check"></i><b>1.2</b> Key contributions</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#the-road-ahead"><i class="fa fa-check"></i><b>1.3</b> The Road Ahead</a></li>
</ul></li>
<li class="part"><span><b>I Foundations</b></span></li>
<li class="chapter" data-level="2" data-path="models.html"><a href="models.html"><i class="fa fa-check"></i><b>2</b> Causal Models</a>
<ul>
<li class="chapter" data-level="2.1" data-path="models.html"><a href="models.html#counterfactualmodel"><i class="fa fa-check"></i><b>2.1</b> The counterfactual model</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="models.html"><a href="models.html#potential-outcomes"><i class="fa fa-check"></i><b>2.1.1</b> Potential outcomes</a></li>
<li class="chapter" data-level="2.1.2" data-path="models.html"><a href="models.html#generalization"><i class="fa fa-check"></i><b>2.1.2</b> Generalization</a></li>
<li class="chapter" data-level="2.1.3" data-path="models.html"><a href="models.html#summaries-of-potential-outcomes"><i class="fa fa-check"></i><b>2.1.3</b> Summaries of potential outcomes</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="models.html"><a href="models.html#causal-models-and-directed-acyclic-graphs"><i class="fa fa-check"></i><b>2.2</b> Causal Models and Directed Acyclic Graphs</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="models.html"><a href="models.html#components-of-a-causal-model"><i class="fa fa-check"></i><b>2.2.1</b> Components of a Causal Model</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="models.html"><a href="models.html#graphing-models-and-using-graphs"><i class="fa fa-check"></i><b>2.3</b> Graphing models and using graphs</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="models.html"><a href="models.html#graphing"><i class="fa fa-check"></i><b>2.3.1</b> Rules for graphing causal models</a></li>
<li class="chapter" data-level="2.3.2" data-path="models.html"><a href="models.html#conditional-independence-from-dags"><i class="fa fa-check"></i><b>2.3.2</b> Conditional independence from DAGs</a></li>
<li class="chapter" data-level="2.3.3" data-path="models.html"><a href="models.html#simplifying-models"><i class="fa fa-check"></i><b>2.3.3</b> Simplifying models</a></li>
<li class="chapter" data-level="2.3.4" data-path="models.html"><a href="models.html#retaining-probabilistic-relations"><i class="fa fa-check"></i><b>2.3.4</b> Retaining probabilistic relations</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="models.html"><a href="models.html#conc2"><i class="fa fa-check"></i><b>2.4</b> Conclusion</a></li>
<li class="chapter" data-level="2.5" data-path="models.html"><a href="models.html#chapter-appendix"><i class="fa fa-check"></i><b>2.5</b> Chapter Appendix</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="models.html"><a href="models.html#steps-for-constructing-causal-models"><i class="fa fa-check"></i><b>2.5.1</b> Steps for constructing causal models</a></li>
<li class="chapter" data-level="2.5.2" data-path="models.html"><a href="models.html#model-construction-in-code"><i class="fa fa-check"></i><b>2.5.2</b> Model construction in code</a></li>
<li class="chapter" data-level="2.5.3" data-path="models.html"><a href="models.html#rules-for-moving-between-levels"><i class="fa fa-check"></i><b>2.5.3</b> Rules for moving between levels</a></li>
<li class="chapter" data-level="2.5.4" data-path="models.html"><a href="models.html#reading-conditional-independence-from-a-graph"><i class="fa fa-check"></i><b>2.5.4</b> Reading conditional independence from a graph</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="illustratemodels.html"><a href="illustratemodels.html"><i class="fa fa-check"></i><b>3</b> Illustrating Causal Models</a>
<ul>
<li class="chapter" data-level="3.1" data-path="illustratemodels.html"><a href="illustratemodels.html#welfare-state-reform"><i class="fa fa-check"></i><b>3.1</b> Welfare state reform</a></li>
<li class="chapter" data-level="3.2" data-path="illustratemodels.html"><a href="illustratemodels.html#military-interventions"><i class="fa fa-check"></i><b>3.2</b> Military Interventions</a></li>
<li class="chapter" data-level="3.3" data-path="illustratemodels.html"><a href="illustratemodels.html#development-and-democratization"><i class="fa fa-check"></i><b>3.3</b> Development and Democratization</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="questions.html"><a href="questions.html"><i class="fa fa-check"></i><b>4</b> Causal Queries</a>
<ul>
<li class="chapter" data-level="4.1" data-path="questions.html"><a href="questions.html#case-level-causal-effects"><i class="fa fa-check"></i><b>4.1</b> Case-level causal effects</a></li>
<li class="chapter" data-level="4.2" data-path="questions.html"><a href="questions.html#case-level-causal-attribution"><i class="fa fa-check"></i><b>4.2</b> Case-level causal attribution</a></li>
<li class="chapter" data-level="4.3" data-path="questions.html"><a href="questions.html#actual-causes"><i class="fa fa-check"></i><b>4.3</b> Actual causes</a></li>
<li class="chapter" data-level="4.4" data-path="questions.html"><a href="questions.html#average-causal-effects"><i class="fa fa-check"></i><b>4.4</b> Average causal effects</a></li>
<li class="chapter" data-level="4.5" data-path="questions.html"><a href="questions.html#causal-paths"><i class="fa fa-check"></i><b>4.5</b> Causal Paths</a></li>
<li class="chapter" data-level="4.6" data-path="questions.html"><a href="questions.html#general-procedure"><i class="fa fa-check"></i><b>4.6</b> General procedure</a></li>
<li class="chapter" data-level="4.7" data-path="questions.html"><a href="questions.html#chapter-appendix-1"><i class="fa fa-check"></i><b>4.7</b> Chapter Appendix</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="bayeschapter.html"><a href="bayeschapter.html"><i class="fa fa-check"></i><b>5</b> Bayesian Answers</a>
<ul>
<li class="chapter" data-level="5.1" data-path="bayeschapter.html"><a href="bayeschapter.html#bayes-basics"><i class="fa fa-check"></i><b>5.1</b> Bayes Basics</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="bayeschapter.html"><a href="bayeschapter.html#simple-instances"><i class="fa fa-check"></i><b>5.1.1</b> Simple instances</a></li>
<li class="chapter" data-level="5.1.2" data-path="bayeschapter.html"><a href="bayeschapter.html#bayes-rule-for-discrete-hypotheses"><i class="fa fa-check"></i><b>5.1.2</b> Bayes’ Rule for Discrete Hypotheses</a></li>
<li class="chapter" data-level="5.1.3" data-path="bayeschapter.html"><a href="bayeschapter.html#bayes-rule-for-continuous-parameters-and-the-dirichlet-family"><i class="fa fa-check"></i><b>5.1.3</b> Bayes’ Rule for Continuous Parameters and The Dirichlet family</a></li>
<li class="chapter" data-level="5.1.4" data-path="bayeschapter.html"><a href="bayeschapter.html#moments"><i class="fa fa-check"></i><b>5.1.4</b> Moments</a></li>
<li class="chapter" data-level="5.1.5" data-path="bayeschapter.html"><a href="bayeschapter.html#bayes-estimation-in-practice"><i class="fa fa-check"></i><b>5.1.5</b> Bayes estimation in practice</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="bayeschapter.html"><a href="bayeschapter.html#bayes-applied"><i class="fa fa-check"></i><b>5.2</b> Bayes applied</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="bayeschapter.html"><a href="bayeschapter.html#simple-bayesian-process-tracing"><i class="fa fa-check"></i><b>5.2.1</b> Simple Bayesian Process Tracing</a></li>
<li class="chapter" data-level="5.2.2" data-path="bayeschapter.html"><a href="bayeschapter.html#a-generalization-bayesian-inference-on-queries"><i class="fa fa-check"></i><b>5.2.2</b> A Generalization: Bayesian Inference on Queries</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="bayeschapter.html"><a href="bayeschapter.html#features-of-bayesian-updating"><i class="fa fa-check"></i><b>5.3</b> Features of Bayesian updating</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="bayeschapter.html"><a href="bayeschapter.html#AppPriors"><i class="fa fa-check"></i><b>5.3.1</b> Priors matter</a></li>
<li class="chapter" data-level="5.3.2" data-path="bayeschapter.html"><a href="bayeschapter.html#simultaneous-joint-updating"><i class="fa fa-check"></i><b>5.3.2</b> Simultaneous, joint updating</a></li>
<li class="chapter" data-level="5.3.3" data-path="bayeschapter.html"><a href="bayeschapter.html#posteriors-are-independent-of-the-ordering-of-data"><i class="fa fa-check"></i><b>5.3.3</b> Posteriors are independent of the ordering of data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="theory.html"><a href="theory.html"><i class="fa fa-check"></i><b>6</b> Theories as causal models</a>
<ul>
<li class="chapter" data-level="6.1" data-path="theory.html"><a href="theory.html#models-as-theories-of"><i class="fa fa-check"></i><b>6.1</b> Models as <em>theories of</em></a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="theory.html"><a href="theory.html#implications-of-structural-causal-models"><i class="fa fa-check"></i><b>6.1.1</b> Implications of structural causal models</a></li>
<li class="chapter" data-level="6.1.2" data-path="theory.html"><a href="theory.html#probabilistic-causal-models"><i class="fa fa-check"></i><b>6.1.2</b> Probabilistic causal models</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="theory.html"><a href="theory.html#theorygains"><i class="fa fa-check"></i><b>6.2</b> Gains from theory</a></li>
<li class="chapter" data-level="6.3" data-path="theory.html"><a href="theory.html#formal-theories-and-causal-models"><i class="fa fa-check"></i><b>6.3</b> Formal theories and causal models</a></li>
</ul></li>
<li class="part"><span><b>II Model-Based Causal Inference</b></span></li>
<li class="chapter" data-level="7" data-path="pt.html"><a href="pt.html"><i class="fa fa-check"></i><b>7</b> Process Tracing with Causal Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="pt.html"><a href="pt.html#process-tracing-and-causal-models"><i class="fa fa-check"></i><b>7.1</b> Process tracing and causal models</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="pt.html"><a href="pt.html#the-intuition"><i class="fa fa-check"></i><b>7.1.1</b> The intuition</a></li>
<li class="chapter" data-level="7.1.2" data-path="pt.html"><a href="pt.html#a-formalization-of-the-general-approach"><i class="fa fa-check"></i><b>7.1.2</b> A formalization of the general approach</a></li>
<li class="chapter" data-level="7.1.3" data-path="pt.html"><a href="pt.html#priors"><i class="fa fa-check"></i><b>7.1.3</b> Priors</a></li>
<li class="chapter" data-level="7.1.4" data-path="pt.html"><a href="pt.html#updating-on-types-given-the-data."><i class="fa fa-check"></i><b>7.1.4</b> Updating on types given the data.</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="pt.html"><a href="pt.html#mapping-from-models-to-classic-qualitative-tests"><i class="fa fa-check"></i><b>7.2</b> Mapping from models to classic qualitative tests</a></li>
<li class="chapter" data-level="7.3" data-path="pt.html"><a href="pt.html#assessing-the-possibility-of-probative-value-from-a-graph"><i class="fa fa-check"></i><b>7.3</b> Assessing the possibility of probative value from a graph</a></li>
<li class="chapter" data-level="7.4" data-path="pt.html"><a href="pt.html#principles-of-learning"><i class="fa fa-check"></i><b>7.4</b> Principles of learning</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="pt.html"><a href="pt.html#a-dag-alone-does-not-guarantee-probative-value-for-a-single-case"><i class="fa fa-check"></i><b>7.4.1</b> A DAG alone does not guarantee probative value for a single case</a></li>
<li class="chapter" data-level="7.4.2" data-path="pt.html"><a href="pt.html#learning-requires-uncertainty"><i class="fa fa-check"></i><b>7.4.2</b> Learning requires uncertainty</a></li>
<li class="chapter" data-level="7.4.3" data-path="pt.html"><a href="pt.html#the-more-specific-the-query-the-more-difficult-it-is-to-gain-leverage"><i class="fa fa-check"></i><b>7.4.3</b> The more specific the query the more difficult it is to gain leverage</a></li>
<li class="chapter" data-level="7.4.4" data-path="pt.html"><a href="pt.html#population-level-uncertainty-does-not-alter-case-level-causal-inference"><i class="fa fa-check"></i><b>7.4.4</b> Population-level uncertainty does not alter case-level causal inference</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ptapp.html"><a href="ptapp.html"><i class="fa fa-check"></i><b>8</b> Process Tracing Application</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ptapp.html"><a href="ptapp.html#inequality-and-democratization-the-debate"><i class="fa fa-check"></i><b>8.1</b> Inequality and Democratization: The Debate</a></li>
<li class="chapter" data-level="8.2" data-path="ptapp.html"><a href="ptapp.html#a-structural-causal-model"><i class="fa fa-check"></i><b>8.2</b> A Structural Causal Model</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="ptapp.html"><a href="ptapp.html#forming-priors"><i class="fa fa-check"></i><b>8.2.1</b> Forming Priors</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="ptapp.html"><a href="ptapp.html#results"><i class="fa fa-check"></i><b>8.3</b> Results</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="ptapp.html"><a href="ptapp.html#inferences-for-cases-with-observed-democratization"><i class="fa fa-check"></i><b>8.3.1</b> Inferences for cases with observed democratization</a></li>
<li class="chapter" data-level="8.3.2" data-path="ptapp.html"><a href="ptapp.html#cases-with-incomplete-data"><i class="fa fa-check"></i><b>8.3.2</b> Cases with incomplete data</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="ptapp.html"><a href="ptapp.html#theory-dependence"><i class="fa fa-check"></i><b>8.4</b> Theory dependence</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="mixing.html"><a href="mixing.html"><i class="fa fa-check"></i><b>9</b> Integrated inferences</a>
<ul>
<li class="chapter" data-level="9.1" data-path="mixing.html"><a href="mixing.html#sample-inference"><i class="fa fa-check"></i><b>9.1</b> Sample inference</a></li>
<li class="chapter" data-level="9.2" data-path="mixing.html"><a href="mixing.html#general-queries"><i class="fa fa-check"></i><b>9.2</b> General queries</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="mixing.html"><a href="mixing.html#set-up"><i class="fa fa-check"></i><b>9.2.1</b> Set up</a></li>
<li class="chapter" data-level="9.2.2" data-path="mixing.html"><a href="mixing.html#inference"><i class="fa fa-check"></i><b>9.2.2</b> Inference</a></li>
<li class="chapter" data-level="9.2.3" data-path="mixing.html"><a href="mixing.html#wrinkles"><i class="fa fa-check"></i><b>9.2.3</b> Wrinkles</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="mixing.html"><a href="mixing.html#mixed-methods"><i class="fa fa-check"></i><b>9.3</b> Mixed methods</a></li>
<li class="chapter" data-level="9.4" data-path="mixing.html"><a href="mixing.html#considerations"><i class="fa fa-check"></i><b>9.4</b> Considerations</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="mixing.html"><a href="mixing.html#probative-value-can-be-derived-from-a-causal-structure-plus-data"><i class="fa fa-check"></i><b>9.4.1</b> Probative value can be derived from a causal structure plus data</a></li>
<li class="chapter" data-level="9.4.2" data-path="mixing.html"><a href="mixing.html#learning-without-identification"><i class="fa fa-check"></i><b>9.4.2</b> Learning without identification</a></li>
<li class="chapter" data-level="9.4.3" data-path="mixing.html"><a href="mixing.html#beyond-binary-data"><i class="fa fa-check"></i><b>9.4.3</b> Beyond binary data</a></li>
<li class="chapter" data-level="9.4.4" data-path="mixing.html"><a href="mixing.html#measurement-error"><i class="fa fa-check"></i><b>9.4.4</b> Measurement error</a></li>
<li class="chapter" data-level="9.4.5" data-path="mixing.html"><a href="mixing.html#spillovers"><i class="fa fa-check"></i><b>9.4.5</b> Spillovers</a></li>
<li class="chapter" data-level="9.4.6" data-path="mixing.html"><a href="mixing.html#clustering"><i class="fa fa-check"></i><b>9.4.6</b> Clustering</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="mixingapp.html"><a href="mixingapp.html"><i class="fa fa-check"></i><b>10</b> Integrated Inferences Application</a>
<ul>
<li class="chapter" data-level="10.1" data-path="mixingapp.html"><a href="mixingapp.html#a-trained-model"><i class="fa fa-check"></i><b>10.1</b> A trained model</a></li>
<li class="chapter" data-level="10.2" data-path="mixingapp.html"><a href="mixingapp.html#data"><i class="fa fa-check"></i><b>10.2</b> Data</a></li>
<li class="chapter" data-level="10.3" data-path="mixingapp.html"><a href="mixingapp.html#inference-1"><i class="fa fa-check"></i><b>10.3</b> Inference</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="mixingapp.html"><a href="mixingapp.html#did-inequality-cause-democratization"><i class="fa fa-check"></i><b>10.3.1</b> Did inequality <em>cause</em> democratization?</a></li>
<li class="chapter" data-level="10.3.2" data-path="mixingapp.html"><a href="mixingapp.html#did-inequality-prevent-democracy"><i class="fa fa-check"></i><b>10.3.2</b> Did inequality <em>prevent</em> democracy?</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="mixingapp.html"><a href="mixingapp.html#from-cases-to-population"><i class="fa fa-check"></i><b>10.4</b> From cases to population</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="mixingapp.html"><a href="mixingapp.html#contribution-to-case-level-inference"><i class="fa fa-check"></i><b>10.4.1</b> Contribution to case-level inference</a></li>
<li class="chapter" data-level="10.4.2" data-path="mixingapp.html"><a href="mixingapp.html#how-much-do-we-get-from-the-model-vs.-the-data"><i class="fa fa-check"></i><b>10.4.2</b> How much do we get from the model vs. the data?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="mm.html"><a href="mm.html"><i class="fa fa-check"></i><b>11</b> Mixing models</a>
<ul>
<li class="chapter" data-level="11.1" data-path="mm.html"><a href="mm.html#a-jigsaw-puzzle-integrating-across-a-model"><i class="fa fa-check"></i><b>11.1</b> A jigsaw puzzle: Integrating across a model</a></li>
<li class="chapter" data-level="11.2" data-path="mm.html"><a href="mm.html#combining-observational-and-experimental-data"><i class="fa fa-check"></i><b>11.2</b> Combining observational and experimental data</a></li>
<li class="chapter" data-level="11.3" data-path="mm.html"><a href="mm.html#transportation-of-findings-across-contexts"><i class="fa fa-check"></i><b>11.3</b> Transportation of findings across contexts</a></li>
<li class="chapter" data-level="11.4" data-path="mm.html"><a href="mm.html#multilevel-models-meta-analysis"><i class="fa fa-check"></i><b>11.4</b> Multilevel models, meta-analysis</a></li>
</ul></li>
<li class="part"><span><b>III Design Choices</b></span></li>
<li class="chapter" data-level="12" data-path="clue.html"><a href="clue.html"><i class="fa fa-check"></i><b>12</b> Clue Selection as a Decision Problem</a>
<ul>
<li class="chapter" data-level="12.1" data-path="clue.html"><a href="clue.html#a-model-informed-approach-to-clue-selection"><i class="fa fa-check"></i><b>12.1</b> A model-informed approach to clue-selection</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="clue.html"><a href="clue.html#clue-selection-with-a-simple-example"><i class="fa fa-check"></i><b>12.1.1</b> Clue selection with a simple example</a></li>
<li class="chapter" data-level="12.1.2" data-path="clue.html"><a href="clue.html#dependence-on-prior-beliefs"><i class="fa fa-check"></i><b>12.1.2</b> Dependence on prior beliefs</a></li>
<li class="chapter" data-level="12.1.3" data-path="clue.html"><a href="clue.html#clue-selection-for-the-democratization-model"><i class="fa fa-check"></i><b>12.1.3</b> Clue selection for the democratization model</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="clue.html"><a href="clue.html#dynamic-strategies"><i class="fa fa-check"></i><b>12.2</b> Dynamic Strategies</a></li>
<li class="chapter" data-level="12.3" data-path="clue.html"><a href="clue.html#conclusion"><i class="fa fa-check"></i><b>12.3</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="caseselection.html"><a href="caseselection.html"><i class="fa fa-check"></i><b>13</b> Case selection for mixed methods inference</a>
<ul>
<li class="chapter" data-level="13.1" data-path="caseselection.html"><a href="caseselection.html#case-selection-strategies"><i class="fa fa-check"></i><b>13.1</b> Case selection strategies</a></li>
<li class="chapter" data-level="13.2" data-path="caseselection.html"><a href="caseselection.html#no-general-rules"><i class="fa fa-check"></i><b>13.2</b> No general rules</a></li>
<li class="chapter" data-level="13.3" data-path="caseselection.html"><a href="caseselection.html#specific-case-walk-through"><i class="fa fa-check"></i><b>13.3</b> Specific case walk through</a></li>
<li class="chapter" data-level="13.4" data-path="caseselection.html"><a href="caseselection.html#simulation-results"><i class="fa fa-check"></i><b>13.4</b> Simulation results</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="caseselection.html"><a href="caseselection.html#models-queries-and-strategies"><i class="fa fa-check"></i><b>13.4.1</b> Models, queries, and strategies</a></li>
<li class="chapter" data-level="13.4.2" data-path="caseselection.html"><a href="caseselection.html#results-1"><i class="fa fa-check"></i><b>13.4.2</b> Results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="wideordeep.html"><a href="wideordeep.html"><i class="fa fa-check"></i><b>14</b> Going wide, going deep</a>
<ul>
<li class="chapter" data-level="14.1" data-path="wideordeep.html"><a href="wideordeep.html#walk-through-of-a-simple-comparison"><i class="fa fa-check"></i><b>14.1</b> Walk-through of a simple comparison</a></li>
<li class="chapter" data-level="14.2" data-path="wideordeep.html"><a href="wideordeep.html#simulation-results-1"><i class="fa fa-check"></i><b>14.2</b> Simulation results</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="wideordeep.html"><a href="wideordeep.html#approach"><i class="fa fa-check"></i><b>14.2.1</b> Approach</a></li>
<li class="chapter" data-level="14.2.2" data-path="wideordeep.html"><a href="wideordeep.html#simulation-results-2"><i class="fa fa-check"></i><b>14.2.2</b> Simulation results</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="wideordeep.html"><a href="wideordeep.html#factoring-in-the-cost-of-data"><i class="fa fa-check"></i><b>14.3</b> Factoring in the cost of data</a></li>
</ul></li>
<li class="part"><span><b>IV Models in Question</b></span></li>
<li class="chapter" data-level="15" data-path="justifying.html"><a href="justifying.html"><i class="fa fa-check"></i><b>15</b> Justifying models</a>
<ul>
<li class="chapter" data-level="15.1" data-path="justifying.html"><a href="justifying.html#justifying-probative-value"><i class="fa fa-check"></i><b>15.1</b> Justifying probative value</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="justifying.html"><a href="justifying.html#nothing-from-nothing"><i class="fa fa-check"></i><b>15.1.1</b> Nothing from nothing</a></li>
<li class="chapter" data-level="15.1.2" data-path="justifying.html"><a href="justifying.html#justifying-the-classic-process-tracing-tests"><i class="fa fa-check"></i><b>15.1.2</b> Justifying the classic process-tracing tests</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="justifying.html"><a href="justifying.html#empirical-discovery-of-causal-structure"><i class="fa fa-check"></i><b>15.2</b> Empirical discovery of causal structure</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="evaluation.html"><a href="evaluation.html"><i class="fa fa-check"></i><b>16</b> Evaluating models</a>
<ul>
<li class="chapter" data-level="16.1" data-path="evaluation.html"><a href="evaluation.html#four-strategies"><i class="fa fa-check"></i><b>16.1</b> Four Strategies</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="evaluation.html"><a href="evaluation.html#check-conditional-independence"><i class="fa fa-check"></i><b>16.1.1</b> Check conditional independence</a></li>
<li class="chapter" data-level="16.1.2" data-path="evaluation.html"><a href="evaluation.html#bayesian-p-value-are-the-data-unexpected-given-your-model"><i class="fa fa-check"></i><b>16.1.2</b> Bayesian <span class="math inline">\(p-\)</span>value: Are the data unexpected given your model?</a></li>
<li class="chapter" data-level="16.1.3" data-path="evaluation.html"><a href="evaluation.html#leave-one-out-loo-cross-validation"><i class="fa fa-check"></i><b>16.1.3</b> Leave-one-out (LOO) cross-validation</a></li>
<li class="chapter" data-level="16.1.4" data-path="evaluation.html"><a href="evaluation.html#sensitivity"><i class="fa fa-check"></i><b>16.1.4</b> Sensitivity</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="evaluation.html"><a href="evaluation.html#evaluating-the-democracy-inequality-model"><i class="fa fa-check"></i><b>16.2</b> Evaluating the Democracy-Inequality model</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="evaluation.html"><a href="evaluation.html#check-assumptions-of-conditional-independence"><i class="fa fa-check"></i><b>16.2.1</b> Check assumptions of conditional independence</a></li>
<li class="chapter" data-level="16.2.2" data-path="evaluation.html"><a href="evaluation.html#bayesian-p-value"><i class="fa fa-check"></i><b>16.2.2</b> Bayesian <span class="math inline">\(p\)</span>-value</a></li>
<li class="chapter" data-level="16.2.3" data-path="evaluation.html"><a href="evaluation.html#loo-validation"><i class="fa fa-check"></i><b>16.2.3</b> LOO validation</a></li>
<li class="chapter" data-level="16.2.4" data-path="evaluation.html"><a href="evaluation.html#sensitivity-to-priors"><i class="fa fa-check"></i><b>16.2.4</b> Sensitivity to priors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="conclusionchapter.html"><a href="conclusionchapter.html"><i class="fa fa-check"></i><b>17</b> Final Words</a>
<ul>
<li class="chapter" data-level="17.1" data-path="conclusionchapter.html"><a href="conclusionchapter.html#the-benefits"><i class="fa fa-check"></i><b>17.1</b> The benefits</a></li>
<li class="chapter" data-level="17.2" data-path="conclusionchapter.html"><a href="conclusionchapter.html#the-worries"><i class="fa fa-check"></i><b>17.2</b> The worries</a></li>
<li class="chapter" data-level="17.3" data-path="conclusionchapter.html"><a href="conclusionchapter.html#the-future"><i class="fa fa-check"></i><b>17.3</b> The future</a></li>
</ul></li>
<li class="part"><span><b>V Appendices</b></span></li>
<li class="chapter" data-level="18" data-path="examplesappendix.html"><a href="examplesappendix.html"><i class="fa fa-check"></i><b>18</b> <code>CausalQueries</code></a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/macartan/CausalQueries/" target="blank">Uses CausalQueries</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Integrated Inferences</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="mixingapp" class="section level1" number="10">
<h1><span class="header-section-number">Chapter 10</span> Integrated Inferences Application</h1>
<!--
:::: {.headerbox data-latex=""}
::: {.center data-latex=""}
:::
We extend the analysis of Chapter \@ref(ptapp) using a model that lets us update about causal processes from data on inequality and democratization from many cases and data on causal processes---mobilization and pressures---from a subset of cases.  We then use the updated model to draw both population-level and case-level inferences.
::::
-->
<p><br></p>
<!-- FLAG: Change causal types to unit types everywhere. -->
<div id="a-trained-model" class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> A trained model</h2>
<p>Whereas in Chapter <a href="ptapp.html#ptapp">8</a> we took the model as given and sought to draw inferences individual cases given data on those cases, the model now becomes an object that we both learn from and learn about. In essence we use the data on many cases to update our beliefs about the general model and then use this “trained” model to make inferences about cases.</p>
<p>Instead of positing a belief over the nodal types for a given case, <span class="math inline">\(\theta\)</span>, we now need to posit a belief over the <em>distribution</em> of nodal types—that is, over <span class="math inline">\(\lambda\)</span>. For instance, whereas in the simple process-tracing model we <em>specified</em> the shares of nodal types for <span class="math inline">\(M\)</span>, we now specify a <em>distribution</em> over the nodal type shares, using a Dirichlet distribution to ensure that the shares across types are always constrained to add up to 1. We do the same, of course, for all nodes. Because we set a prior distribution over nodal types (rather than fixed proportions), we can now update on these population-level distributions as the model confronts data.</p>
<p>The same applies to beliefs about confounding. Recall that we allow for unobserved confounding by allowing <span class="math inline">\(\lambda\)</span> to include beliefs about the <em>joint</em> distributions of nodal types, and we set priors on these joint distributions as well. In the application below, we focus on potential confounding in the relationship between inequality and mobilization: the possibility that inequality may be more or less likely in places where inequality would induce mobilization. Here we do not express informed prior beliefs about the direction or magnitude of such confounding; we set up the parameter matrix to allow for the possibility of confounding and set a flat prior over its direction and magnitude. We can, in turn, learn about confounding from the data.</p>
<p>We begin with the same basic model as we used in Chapter <a href="ptapp.html#ptapp">8</a>, with inequality (<span class="math inline">\(I\)</span>) potentially affecting democratization (<span class="math inline">\(D\)</span>) both through a direct pathway and through an indirect pathway mediated by mobilization (<span class="math inline">\(M\)</span>). International pressure (<span class="math inline">\(P\)</span>) is also a “parent” of democratization.</p>
<p>Further, we impose the same set of qualitative restrictions, ruling out a negative effect of inequality on mobilization, a direct positive effect of inequality on democratization, a negative effect of mobilization on democracy, and a negative effect of pressure on democratization. Note that this setup allows for inequality to have a positive (through mobilization) effect on democratization, a negative (direct) effect on democratization, or no effect at all.</p>
<p>Finally, we allow for confounding. The theoretical intuition we want to instantiate in the model is that the level of inequality could be endogenous to inequality’s effect on mobilization. In particular, in places where mobilization would pose a mobilizational threat, governments may work harder to reduce inequality. To allow for this possibility, we need to create distinct elements of <span class="math inline">\(\lambda\)</span> representing the conditional distribution of <span class="math inline">\(I\)</span>’s nodal types given <span class="math inline">\(M\)</span>’s: one parameter for <span class="math inline">\(\theta^I\)</span>’s distribution when <span class="math inline">\(M\)</span>’s nodal type is <span class="math inline">\(\theta^M_{01}\)</span>, and another parameter for <span class="math inline">\(\theta^I\)</span>’s distribution when <span class="math inline">\(M\)</span>’s nodal type is something else.</p>
<p>This model, with confounding, is represented graphically as in Figure <a href="mixingapp.html#fig:pimdgraph">10.1</a>. The possibility of confounding is represented with the bidirected edge, connecting <span class="math inline">\(I\)</span> and <span class="math inline">\(M\)</span>.</p>
<div class="figure"><span style="display:block;" id="fig:pimdgraph"></span>
<img src="ii_files/figure-html/pimdgraph-1.png" alt="Democracy and Inequality Model" width="672" />
<p class="caption">
Figure 10.1: Democracy and Inequality Model
</p>
</div>
</div>
<div id="data" class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> Data</h2>
<p>As in Chapter <a href="ptapp.html#ptapp">8</a>, we will confront the model with data drawn from our coding of the case narratives in the Supplementary Material for <span class="citation"><a href="#ref-haggard2012inequality" role="doc-biblioref">Haggard and Kaufman</a> (<a href="#ref-haggard2012inequality" role="doc-biblioref">2012</a>)</span>. However, rather than implementing the analysis case-by-case, we now derive leverage from the joint distribution of the data available across all cases.</p>
<p>Table <a href="mixingapp.html#tab:data82">10.1</a> gives a snapshot of the data.</p>
<table>
<caption><span id="tab:data82">Table 10.1: </span>Data (snapshot) derived from Haggard and Kaufman (2012)</caption>
<thead>
<tr class="header">
<th align="left">Case</th>
<th align="right">P</th>
<th align="right">I</th>
<th align="right">M</th>
<th align="right">D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan</td>
<td align="right"></td>
<td align="right">1</td>
<td align="right"></td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Albania</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">Algeria</td>
<td align="right"></td>
<td align="right">0</td>
<td align="right"></td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Angola</td>
<td align="right"></td>
<td align="right">1</td>
<td align="right"></td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Argentina</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">Bangladesh</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
<p>Note that this is not a rectangular dataset in that Haggard and Kaufman’s collection of clues was conditional on the outcome, <span class="math inline">\(D=1\)</span>: they gathered qualitative data on the presence of international pressure and the presence of mass-mobilization <em>only</em> for those cases that democratized. This is not an uncommon case-selection principle. The analyst often reasons that more can be learned about how an outcome arises by focusing in on cases where the outcome of interest has in fact occurred. (We assess this case-selection intuition, in the context of model-based inferences, in Chapter <a href="caseselection.html#caseselection">13</a>.)</p>
<p>The raw correlations between variables is shown in Table <a href="mixingapp.html#tab:pimdcorr">10.2</a>. Some correlations are missing because, as mentioned, data on some variables were only gathered conditional on the values of others. For those quantities where we do see correlations, they are not especially strong. There is, in particular, a weak overall relationship between inequality and democratization — though, of course, this is consistent with inequality having heterogeneous effects across the sample. The strongest correlation in the data is between <span class="math inline">\(P\)</span> and <span class="math inline">\(M\)</span>, which are assumed to be uncorrelated in the model, though this correlation is also quite weak.</p>
<table>
<caption><span id="tab:pimdcorr">Table 10.2: </span>Pairwise correlated in the democracy-inequality (PIMD) data. P = Pressure, I = Inequality, M = Mobilization, D = Democratization</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">P</th>
<th align="right">I</th>
<th align="right">M</th>
<th align="right">D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">P</td>
<td align="right">1.000</td>
<td align="right">0.157</td>
<td align="right">-0.177</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">I</td>
<td align="right">0.157</td>
<td align="right">1.000</td>
<td align="right">0.114</td>
<td align="right">-0.154</td>
</tr>
<tr class="odd">
<td align="left">M</td>
<td align="right">-0.177</td>
<td align="right">0.114</td>
<td align="right">1.000</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">D</td>
<td align="right"></td>
<td align="right">-0.154</td>
<td align="right"></td>
<td align="right">1.000</td>
</tr>
</tbody>
</table>
</div>
<div id="inference-1" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> Inference</h2>
<p>With data and model in hand, we can now update our model to get posteriors on the distribution <span class="math inline">\(\lambda\)</span> from which we can generate beliefs over all causal relations.
<!-- FLAG: Need to talk a bit through what's happening here.  --></p>
<!--
:::: {.headerbox data-latex=""}
::: {.center data-latex=""}
:::

The code below shows how to define the Democratization model in `CausalQueries`.

The first line provides the DAG and indicated confounding between I and M. The second line imposes monotonicity restrictions. 


```r
model <- 
  
  make_model("I -> M -> D <- P; I -> D; I <-> M") %>% 
  
  set_restrictions(c( 
           "(M[I=1] < M[I=0])", 
           "(D[I=1] > D[I=0]) | (D[M=1] < D[M=0]) | (D[P=1] < D[P=0])"))
```

We can then figure out the set of parameters needed to characterize all possible causal relations between these nodes that are consistent with the model. These parameters are used to specify a likelihood function, which, combined with priors on parameters and the data lets us update on the distribution of causal relations. In `CausalQueries` all this is done using `update_model()`.


```r
model <- update_model(model, data)
```



::::
-->
<p><br></p>
<p>What do we find?</p>
<div id="did-inequality-cause-democratization" class="section level3" number="10.3.1">
<h3><span class="header-section-number">10.3.1</span> Did inequality <em>cause</em> democratization?</h3>
<p>We have used the data to update on <span class="math inline">\(\lambda\)</span>: our beliefs about the distributions of nodal types, including about their joint distributions (i.e., confounding). We first use this to make claims about types, similar to what we did in Chapter 8 but now with a model that has been trained on data.</p>
<p>In Table <a href="mixingapp.html#tab:HK10cases1">10.3</a> we first ask what we would now infer about cases given democratization and low inequality and different observations on mobilization and international pressure. This table is the analogue of Table REF in Chapter 8.</p>
<table>
<caption><span id="tab:HK10cases1">Table 10.3: </span>Four cases with low inequality and democratization. Question of interest: Was low inequality a cause of democracy? Table shows posterior beliefs for different data for four cases given information on <span class="math inline">\(M\)</span> or <span class="math inline">\(P\)</span>. Data from Haggard and Kaufman (2012). Analyses here use a model with assumptions on monotonic effects but magnitudes of effects updated from data.</caption>
<thead>
<tr class="header">
<th align="left">Case</th>
<th align="left">M: Mobilization?</th>
<th align="left">P: Pressure?</th>
<th align="left">No clues</th>
<th align="left">M only</th>
<th align="left">P only</th>
<th align="left">M and P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Mexico (2000)</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">0.438</td>
<td align="left">0.475</td>
<td align="left">0.615</td>
<td align="left">0.667</td>
</tr>
<tr class="even">
<td align="left">Taiwan (1996)</td>
<td align="left">0</td>
<td align="left">1</td>
<td align="left">0.438</td>
<td align="left">0.475</td>
<td align="left">0.34</td>
<td align="left">0.393</td>
</tr>
<tr class="odd">
<td align="left">Albania (1991)</td>
<td align="left">1</td>
<td align="left">0</td>
<td align="left">0.438</td>
<td align="left">0.394</td>
<td align="left">0.615</td>
<td align="left">0.571</td>
</tr>
<tr class="even">
<td align="left">Nicaragua (1984)</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">0.438</td>
<td align="left">0.394</td>
<td align="left">0.34</td>
<td align="left">0.263</td>
</tr>
</tbody>
</table>
<p>In Table <a href="mixingapp.html#tab:HK10cases1">10.3</a> we ask what we would now infer about cases given democratization and <em>high</em> inequality and different observations on mobilization and international pressure. This table is the analogue of Table REF in Chapter 8.</p>
<table>
<caption><span id="tab:HK10cases2">Table 10.4: </span>Four cases with high inequality and democratization. Question of interest: Was high inequality a cause of democratization? Table shows posterior beliefs for different data for 4 cases given information on <span class="math inline">\(M\)</span> or <span class="math inline">\(P\)</span>. Data from Haggard and Kaufman (2012). Analyses here use a model with assumptions on monotonic effects but magnitudes of effects updated from data.r</caption>
<thead>
<tr class="header">
<th align="left">Case</th>
<th align="left">M: Mobilization?</th>
<th align="left">P: Pressure?</th>
<th align="left">No clues</th>
<th align="left">M only</th>
<th align="left">P only</th>
<th align="left">M and P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Mongolia (1990)</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">0.128</td>
<td align="left">0</td>
<td align="left">0.231</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="left">Paraguay (1989)</td>
<td align="left">0</td>
<td align="left">1</td>
<td align="left">0.128</td>
<td align="left">0</td>
<td align="left">0.088</td>
<td align="left">0</td>
</tr>
<tr class="odd">
<td align="left">Sierra Leone (1996)</td>
<td align="left">1</td>
<td align="left">0</td>
<td align="left">0.128</td>
<td align="left">0.15</td>
<td align="left">0.231</td>
<td align="left">0.25</td>
</tr>
<tr class="even">
<td align="left">Malawi (1994)</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">0.128</td>
<td align="left">0.15</td>
<td align="left">0.088</td>
<td align="left">0.107</td>
</tr>
</tbody>
</table>
</div>
<div id="did-inequality-prevent-democracy" class="section level3" number="10.3.2">
<h3><span class="header-section-number">10.3.2</span> Did inequality <em>prevent</em> democracy?</h3>
<p>As before we can also ask questions about causes that have not democratized – even though we have no additional data about these cases in particular.</p>
<table>
<caption><span id="tab:Tapp101">Table 10.5: </span>No inequality and No democratization: Was no inequality a cause of no democratization? Analyses here use priors assuming only monotonic effects.</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">P</th>
<th align="right">M</th>
<th align="right">posterior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">I0P0M0D0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.122</td>
</tr>
<tr class="even">
<td align="left">I0P1M0D0</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.259</td>
</tr>
<tr class="odd">
<td align="left">I0P0M1D0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">I0P1M1D0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">I0M0D0</td>
<td align="right"></td>
<td align="right">0</td>
<td align="right">0.139</td>
</tr>
<tr class="even">
<td align="left">I0M1D0</td>
<td align="right"></td>
<td align="right">1</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">I0P0D0</td>
<td align="right">0</td>
<td align="right"></td>
<td align="right">0.097</td>
</tr>
<tr class="even">
<td align="left">I0P1D0</td>
<td align="right">1</td>
<td align="right"></td>
<td align="right">0.233</td>
</tr>
<tr class="odd">
<td align="left">I0D0</td>
<td align="right"></td>
<td align="right"></td>
<td align="right">0.112</td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:Tapp102">Table 10.6: </span>Inequality and No democratization: Was inequality a cause of no democratization? Analyses here use priors assuming only monotonic effects.</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">P</th>
<th align="right">M</th>
<th align="right">posterior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">I1P0M0D0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.247</td>
</tr>
<tr class="even">
<td align="left">I1P1M0D0</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.565</td>
</tr>
<tr class="odd">
<td align="left">I1P0M1D0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.393</td>
</tr>
<tr class="even">
<td align="left">I1P1M1D0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0.655</td>
</tr>
<tr class="odd">
<td align="left">I1M0D0</td>
<td align="right"></td>
<td align="right">0</td>
<td align="right">0.309</td>
</tr>
<tr class="even">
<td align="left">I1M1D0</td>
<td align="right"></td>
<td align="right">1</td>
<td align="right">0.424</td>
</tr>
<tr class="odd">
<td align="left">I1P0D0</td>
<td align="right">0</td>
<td align="right"></td>
<td align="right">0.313</td>
</tr>
<tr class="even">
<td align="left">I1P1D0</td>
<td align="right">1</td>
<td align="right"></td>
<td align="right">0.594</td>
</tr>
<tr class="odd">
<td align="left">I1D0</td>
<td align="right"></td>
<td align="right"></td>
<td align="right">0.359</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="from-cases-to-population" class="section level2" number="10.4">
<h2><span class="header-section-number">10.4</span> From cases to population</h2>
<p>One set of questions we can ask of the updated model is about the probability that high inequality causes democratization. We can pose this question at different levels of conditioning. For instance, we can ask:</p>
<ol style="list-style-type: decimal">
<li><p><strong>For all cases</strong>. For what proportion of cases in the population does inequality have a positive effect on democratization?</p></li>
<li><p><strong>For all cases displaying a given causal state and outcome</strong>. Looking specifically at those cases that in fact had high inequality and democratized, for what proportion was the high inequality a cause of democratization?</p></li>
<li><p><strong>For cases displaying a given causal state and outcome, and with additional clues present or absent.</strong> What if we have also collected clues on mediating or moderating nodes? For instance, for what proportion of high-inequality, democratizing cases <em>with</em> mobilization did inequality cause the outcome? For what proportion <em>without</em> mobilization? Likewise for the presence or absence of international pressure? Importantly, comparing a given estimate with and without a given clue amounts to an assessment of the clue’s probative value.</p></li>
</ol>
<p>We ask <code>CausalQueries</code> now to query <span class="math inline">\(\lambda\)</span>’s posterior distribution to generate posterior distributions for each of these quantities. We can define our queries quite simply in terms of the causal types that correspond to the effect of interest and then take the conditional probability of these. We present the code and results of these operations below and in Figure <a href="mixingapp.html#fig:mixedhist">10.2</a>.</p>
<!-- FLAG: Not sure how much it is worth saying here substantively about the results given how strongly they are driven by the restrictions. -->
<table>
<caption><span id="tab:unnamed-chunk-23">Table 10.7: </span>Probability that inequality increases chances of democratization given:</caption>
<thead>
<tr class="header">
<th align="left">Given</th>
<th align="right">mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">-</td>
<td align="right">0.04</td>
</tr>
<tr class="even">
<td align="left">D==1 &amp; I==1</td>
<td align="right">0.11</td>
</tr>
<tr class="odd">
<td align="left">D==1 &amp; I==1 &amp; M==1</td>
<td align="right">0.16</td>
</tr>
<tr class="even">
<td align="left">D==1 &amp; I==1 &amp; M==0</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">D==1 &amp; I==1 &amp; M==1 &amp; P==1</td>
<td align="right">0.09</td>
</tr>
<tr class="even">
<td align="left">D==1 &amp; I==1 &amp; M==1 &amp; P==0</td>
<td align="right">0.20</td>
</tr>
</tbody>
</table>
<p>In figure <a href="mixingapp.html#fig:mixedhist">10.2</a>, we graph the priors for each of these queries next to the posteriors.</p>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value
## with `binwidth`.</code></pre>
<div class="figure"><span style="display:block;" id="fig:mixedhist"></span>
<img src="ii_files/figure-html/mixedhist-1.png" alt="Posteriors on Causes of Democratization" width="672" />
<p class="caption">
Figure 10.2: Posteriors on Causes of Democratization
</p>
</div>
<p>We can see that the share of cases overall in which inequality causes democratization is estimated to be very low, with a good deal of confidence. The proportion is considerably higher for those cases that in fact experienced high inequality and democratization. The proportion of positive causal effects is believed to be even higher for those in which mobilization occurred. Moreover, the proportion of <span class="math inline">\(I=1, D=1\)</span> cases with a positive effect of inequality on democratization is even higher when an alternative cause—international pressure—is absent, though our uncertainty about this share is also very high.</p>
<p>We also see that the absence of mobilization tells us for certain that democratization was not caused by inequality. Interestingly, however, this result derives purely from the model restrictions, rather than from the data: under the restrictions we imposed, a positive effect of inequality can operate <em>only</em> through mobilization.</p>
<p>Turning now to the cases in which democratization did not occur, Figure <a href="mixingapp.html#fig:mixedhist2">10.3</a> asks for what proportion of cases overall inequality has a negative effect on democratization; for what proportion of <span class="math inline">\(I=1, D=0\)</span> cases inequality prevented democratization; and this latter query conditional on different clue realizations.</p>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value
## with `binwidth`.</code></pre>
<div class="figure"><span style="display:block;" id="fig:mixedhist2"></span>
<img src="ii_files/figure-html/mixedhist2-1.png" alt="Posteriors on Causes of Democratization" width="672" />
<p class="caption">
Figure 10.3: Posteriors on Causes of Democratization
</p>
</div>
<p>We see that inequality appears, overall, more commonly to prevent democratization than to cause it. We are, moreover, most confident that inequality played a preventive role in those cases in which there was mobilization and international pressure—both of which <em>could</em> have generated democratization—but still no democratization occurred.</p>
<div id="contribution-to-case-level-inference" class="section level3" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> Contribution to case-level inference</h3>
<p>There are two ways of thinking about the learning we derive from the above estimates. On the one hand, we can think of our estimands in population-level terms. The results in Figures <a href="mixingapp.html#fig:mixedhist">10.2</a> and <a href="mixingapp.html#fig:mixedhist2">10.3</a> can be understood as our estimates of the <em>share</em> of cases in the population, with a given set of characteristics, for which a particular causal effect holds.</p>
<p>Yet these distributions, by the very same token, represent our beliefs about the probability that <span class="math inline">\(I\)</span> had a positive or negative (depending on the query we are talking about) causal effect in an individual case for which we have seen a given data pattern. Thus, for instance, from Figure <a href="mixingapp.html#fig:mixedhist">10.2</a> we can see our posterior belief about the proportion of <span class="math inline">\(I=D=M=1\)</span> cases in the population for which <span class="math inline">\(I=1\)</span> caused <span class="math inline">\(D=1\)</span>. But this also tells us, for an individual case randomly selected from the population of <span class="math inline">\(I=D=M=1\)</span> cases, the probability that high inequality caused democratization in the case. To put the point differently, suppose we want to know whether <span class="math inline">\(I=1\)</span> was a cause of <span class="math inline">\(D=1\)</span> in a randomly selected case, so we do process tracing and observe <span class="math inline">\(M=1\)</span>: this same estimate answers the case-level query, telling us the probability that <span class="math inline">\(I=1\)</span> caused <span class="math inline">\(D=1\)</span> in the case at hand.</p>
<p>The key difference between case-level inference from mixed data and the pure process-tracing setup from Chapter <a href="ptapp.html#ptapp">8</a> is that now our case-level inferences are informed by <em>data</em> from the population, rather than merely by a set of prior beliefs about the population. Consider, for instance, the difference in posteriors on the probability of a negative effect for the query for <span class="math inline">\(I=1, D=0\)</span> given <span class="math inline">\(M=0\)</span> (mean of about 0.31) as compared to the query for <span class="math inline">\(I=1, D=0\)</span> given <span class="math inline">\(M=1\)</span> (about 0.42). That difference in what we believe depending on <span class="math inline">\(M\)</span>’s value represents the probative value of the <span class="math inline">\(M\)</span> clue given the model as <em>updated</em> from the data. Of course, we have also made assumptions in building the model, including motonicity restrictions, and we speak to their role below. But the general point is that, in mixed-data inference, we can learn empirically about the probative value of any given node, rather than drawing probative value purely from theory.</p>
</div>
<div id="how-much-do-we-get-from-the-model-vs.-the-data" class="section level3" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> How much do we get from the model vs. the data?</h3>
<p>We might wonder, at the same time, how much we are in fact learning from the data, as compared to what we built into the model at the outset, including through the monotonicity restrictions that we imposed. To examine this, in Figures <a href="mixingapp.html#fig:dcaused">10.4</a> and <a href="mixingapp.html#fig:dprevented">10.5</a>, we plot the mean (and one-standard-deviation error bars) of our prior and our posterior on the same set of queries. We see that there is almost no shift in beliefs for the positive-effect queries, with a somewhat greater shift in means for the negative-effect queries. However, our uncertainty about negative effects shrinks some, though remains quite high.</p>
<p>By comparing the prior and posterior estimates given <span class="math inline">\(M=1\)</span> and given <span class="math inline">\(M=0\)</span>, we can also assess whether we have learned about <span class="math inline">\(M\)</span>’s informativeness. We see that, in this example, we do not happen to learn anything from the data about <span class="math inline">\(M\)</span>’s probative value: the difference in beliefs between each estimate given <span class="math inline">\(M=1\)</span> and that estimate given <span class="math inline">\(M=0\)</span> remains about the same in our posteriors as it was in our priors.</p>
<div class="figure"><span style="display:block;" id="fig:dcaused"></span>
<img src="ii_files/figure-html/dcaused-1.png" alt="Priors and posteriors on the probability that inequality caused democratization (probability that I has a positive effect on D) given different kinds of observed case-level data. The error bars show plus or minus one standard deviation of the posterior variance. " width="672" />
<p class="caption">
Figure 10.4: Priors and posteriors on the probability that inequality caused democratization (probability that I has a positive effect on D) given different kinds of observed case-level data. The error bars show plus or minus one standard deviation of the posterior variance.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:dprevented"></span>
<img src="ii_files/figure-html/dprevented-1.png" alt="Priors and posteriors on the probability that inequality prevented democratization (probability that I has a negative effect on D) given different kinds of observed case-level data. The error bars show plus or minus one standard deviation of the respective distribution's variance." width="672" />
<p class="caption">
Figure 10.5: Priors and posteriors on the probability that inequality prevented democratization (probability that I has a negative effect on D) given different kinds of observed case-level data. The error bars show plus or minus one standard deviation of the respective distribution’s variance.
</p>
</div>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-haggard2012inequality" class="csl-entry">
Haggard, Stephan, and Robert R Kaufman. 2012. <span>“Inequality and Regime Change: Democratic Transitions and the Stability of Democratic Rule.”</span> <em>American Political Science Review</em> 106 (03): 495–516.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="mixing.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mm.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false,
"google": false,
"instapper": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["ii.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"toolbar": {
"position": "static"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
